traindata_path: "data/training_data_CACC.pkl"

traindata_path_client_1: "data/FL_data/type1_data.pkl"
traindata_path_client_2: "data/FL_data/type2_data.pkl"
traindata_path_client_3: "data/FL_data/type3_data.pkl"

#models
Predictor:
  batch_size: 128
  num_epochs: 40
  window_size: 50
  period: 10
  min_path: "model/normorlize_min_DVA_prd.npy"
  max_path: "model/normorlize_max_DVA_prd.npy"
  learning_rate: 0.0001

  hidden_size: 120
  input_size: 6
  output_size: 3
